"""Routes related to processing corpora with Sparv."""

import time

from fastapi import APIRouter, Depends, Query, status
from fastapi.responses import JSONResponse

from mink.core import exceptions, models, registry, return_codes, route_utils, utils
from mink.core.resource_specs import get_spec
from mink.core.status import Status
from mink.sb_auth import login
from mink.sparv import processing
from mink.sparv.spec import CORPUS, ProcessName
from mink.sparv.storage import storage

router = APIRouter(tags=["Manage Corpora"], prefix="/corpus")
sbauth_corpus = get_spec(CORPUS).sbauth_resource_type
corpus = str(CORPUS)
AUTH_CORPUS_WRITE = login.AuthDependency(min_level="WRITE", sbauth_resource_type=sbauth_corpus, resource_type=corpus)


@router.put(
    "/job/run/{resource_id}",
    operation_id="run-corpus-job",
    response_model=models.StatusResponse,
    responses={
        **models.common_auth_error_responses,
        status.HTTP_400_BAD_REQUEST: {
            "model": models.BaseErrorResponse,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.INVALID_CONFIG.message,
                        "return_code": return_codes.INVALID_CONFIG.code,
                        "info": "The importer in your config file is incompatible with your source files",
                        "current_importer": "text_import",
                        "expected_importer": "xml_import",
                    }
                }
            },
        },
        status.HTTP_404_NOT_FOUND: {
            "model": models.ErrorResponse404File,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FILE_NOT_FOUND.message,
                        "return_code": return_codes.FILE_NOT_FOUND.code,
                        "info": "No source files found for this resource",
                    }
                }
            },
        },
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": models.ErrorResponse500,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FAILED_QUEUING.message,
                        "return_code": return_codes.FAILED_QUEUING.code,
                        "info": "BaseException",
                    }
                }
            },
        },
    },
)
async def run_sparv(
    exports: list[str] | None = Query(None, description="Sparv exports to produce"),
    files: list[str] | None = Query(None, description="Source files to process"),
    auth_data: dict = Depends(AUTH_CORPUS_WRITE),
) -> JSONResponse:
    """Add a Sparv annotation job for the corpus to the queue.

    The requested export formats may be supplied as a comma-separated list to the `exports` parameter. If no export
    formats are specified, the `xml_export:pretty` export will be generated by default.

    The `files` parameter can be used to run the pipeline on a part of the corpus. The key to `files` is a
    comma-separated list of file names without file extensions, e.g. `files=dokument1,dokument2`.

    There can only be one active job (annotation or installation) for each corpus at a time. A job must finish or be
    aborted before a new one can be started.

    ### Example

    ```bash
    curl -X PUT '{{host}}/corpus/job/run/<resource_id>?exports=csv_export:csv,stats_export:freq_list,\
xml_export:pretty' -H 'Authorization: Bearer YOUR_JWT'
    ```
    """
    try:
        info_item = route_utils.get_info_from_auth(auth_data)
    except Exception as e:
        raise exceptions.MinkHTTPException(return_code=return_codes.FAILED_RUNNING, info=str(e)) from e
    processing.run_sparv(info_item, exports, files)

    # Wait a few seconds to check whether anything terminated early
    time.sleep(3)
    return utils.response(return_code=return_codes.CHECKED_STATUS, **route_utils.make_status_response(info_item))


@router.post(
    "/job/abort/{resource_id}",
    operation_id="abort-corpus-job",
    response_model=models.BaseResponse,
    responses={
        status.HTTP_200_OK: {
            "content": {
                "application/json": {
                    "example": {
                        "status": "success",
                        "message": return_codes.ABORTED_JOB.message,
                        "return_code": return_codes.ABORTED_JOB.code,
                    }
                }
            }
        },
        **models.common_auth_error_responses,
        status.HTTP_404_NOT_FOUND: {
            "model": models.ErrorResponse404File,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.NO_RUNNING_JOB.message,
                        "return_code": return_codes.NO_RUNNING_JOB.code,
                    }
                }
            },
        },
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": models.ErrorResponse500,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FAILED_ABORTING.message,
                        "return_code": return_codes.FAILED_ABORTING.code,
                        "info": "BaseException",
                    }
                }
            },
        },
        status.HTTP_503_SERVICE_UNAVAILABLE: {
            "model": models.BaseErrorResponse,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.PROCESS_RUNNING.message,
                        "return_code": return_codes.PROCESS_RUNNING.code,
                        "info": "Cannot abort job while syncing files",
                    }
                }
            },
        },
    },
)
async def abort_job(auth_data: dict = Depends(AUTH_CORPUS_WRITE)) -> JSONResponse:
    """Abort the currently running job for the corpus.

    If the job is in the queue but not yet running, it will be removed from the queue. If the job is running, it will be
    stopped.

    ### Example

    ```bash
    curl -X POST '{{host}}/corpus/job/abort/<resource_id>' -H 'Authorization: Bearer YOUR_JWT'
    ```
    """
    info_item = registry.get(auth_data["resource_id"])
    job = processing.abort_job(info_item)
    return utils.response(return_code=return_codes.ABORTED_JOB, job_status=job.status.serialize())


@router.delete(
    "/annotations/remove/{resource_id}",
    operation_id="clear-corpus-annotations",
    response_model=models.BaseResponse,
    responses={
        status.HTTP_200_OK: {
            "content": {
                "application/json": {
                    "example": {
                        "status": "success",
                        "message": return_codes.REMOVED_CONTENT.message,
                        "return_code": return_codes.REMOVED_CONTENT.code,
                        "info": "Removed annotations",
                        "sparv_output": "'sparv-workdir' directory removed",
                    }
                }
            }
        },
        **models.common_auth_error_responses,
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": models.ErrorResponse500,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FAILED_REMOVING_CONTENT.message,
                        "return_code": return_codes.FAILED_REMOVING_CONTENT.code,
                        "info": "Failed to remove annotations",
                    }
                }
            },
        },
        status.HTTP_503_SERVICE_UNAVAILABLE: {
            "model": models.BaseErrorResponse,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.PROCESS_RUNNING.message,
                        "return_code": return_codes.PROCESS_RUNNING.code,
                        "info": "Cannot clear annotations while a job is running",
                    }
                }
            },
        },
    },
)
async def clear_annotations(auth_data: dict = Depends(AUTH_CORPUS_WRITE)) -> JSONResponse:
    """Remove all annotation files for the corpus from the Sparv server.

    This action cannot be performed while a job is running.

    ### Example

    ```bash
    curl -X DELETE '{{host}}/corpus/annotations/remove/<resource_id>' -H 'Authorization: Bearer YOUR_JWT'
    ```
    """
    resource_id = auth_data["resource_id"]
    # Check if there is an active job
    job = processing.require_job(registry.get(resource_id).job)
    if job.status.is_running():
        raise exceptions.MinkHTTPException(
            return_code=return_codes.PROCESS_RUNNING, info="Cannot clear annotations while a job is running"
        )

    try:
        sparv_output = job.clean()
        return utils.response(
            return_code=return_codes.REMOVED_CONTENT, info="Removed annotations", sparv_output=sparv_output
        )
    except Exception as e:
        raise exceptions.MinkHTTPException(
            return_code=return_codes.FAILED_REMOVING_CONTENT, info=f"Failed to remove annotations: {e}"
        ) from e


@router.put(
    "/korp/install/{resource_id}",
    operation_id="install-korp",
    response_model=models.StatusResponse,
    responses={
        **models.common_auth_error_responses,
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": models.ErrorResponse500,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FAILED_QUEUING.message,
                        "return_code": return_codes.FAILED_QUEUING.code,
                        "info": "BaseException",
                    }
                }
            },
        },
    },
)
async def install_korp(
    scramble: bool = Query(False, description="Indicates whether the corpus should be scrambled in Korp"),
    auth_data: dict = Depends(AUTH_CORPUS_WRITE),
) -> JSONResponse:
    """Install the corpus in Korp with Sparv.

    The `scramble` parameter can be used to scramble the corpus data before installation.

    ### Example

    ```bash
    curl -X PUT '{{host}}/corpus/korp/install/<resource_id>?scramble=true' -H 'Authorization: Bearer YOUR_JWT'
    ```
    """
    resource_id = auth_data["resource_id"]

    # Get info_item, check for changes and remove exports if necessary
    sources_deleted = config_changed = False
    try:
        info_item = route_utils.get_info_from_auth(auth_data)
        if info_item.job.started:
            _, sources_deleted, config_changed = storage.get_file_changes(resource_id, info_item)
    except Exception as e:
        raise exceptions.MinkHTTPException(return_code=return_codes.FAILED_RUNNING, info=str(e)) from e
    if sources_deleted or config_changed:
        sparv_output = ""
        try:
            job = processing.require_job(info_item.job)
            success, sparv_output = job.clean_export()
            assert success
        except Exception as e:
            raise exceptions.MinkHTTPException(
                return_code=return_codes.FAILED_RUNNING,
                info=f"Failed to remove outdated export files before running Sparv: {e}",
                sparv_message=sparv_output,
            ) from e

    # Queue job
    job = processing.require_job(info_item.job)
    job.set_attribute("install_scrambled", scramble)
    try:
        job = registry.add_to_queue(job)
    except Exception as e:
        raise exceptions.MinkHTTPException(return_code=return_codes.FAILED_QUEUING, info=str(e)) from e

    job.set_status(Status.waiting, ProcessName.korp)

    # Wait a few seconds to check whether anything terminated early
    time.sleep(3)
    return utils.response(return_code=return_codes.CHECKED_STATUS, **route_utils.make_status_response(info_item))


@router.delete(
    "/korp/uninstall/{resource_id}",
    operation_id="uninstall-korp",
    response_model=models.BaseResponse,
    responses={
        status.HTTP_200_OK: {
            "content": {
                "application/json": {
                    "example": {
                        "status": "success",
                        "message": return_codes.UNINSTALLED.message,
                        "return_code": return_codes.UNINSTALLED.code,
                        "info": "Uninstalled from Korp",
                    }
                }
            }
        },
        **models.common_auth_error_responses,
        status.HTTP_503_SERVICE_UNAVAILABLE: {
            "model": models.BaseErrorResponse,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.PROCESS_RUNNING.message,
                        "return_code": return_codes.PROCESS_RUNNING.code,
                        "info": "Cannot uninstall while a job is running",
                    }
                }
            },
        },
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": models.ErrorResponse500,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FAILED_UNINSTALLING.message,
                        "return_code": return_codes.FAILED_UNINSTALLING.code,
                        "info": "Error when uninstalling from Korp",
                    }
                }
            },
        },
    },
)
async def uninstall_korp(auth_data: dict = Depends(AUTH_CORPUS_WRITE)) -> JSONResponse:
    """Uninstall the corpus from Korp with Sparv.

    ### Example

    ```bash
    curl -X DELETE '{{host}}/corpus/korp/uninstall/<resource_id>' -H 'Authorization: Bearer YOUR_JWT'
    ```
    """
    resource_id = auth_data["resource_id"]
    # Check if there is an active job
    job = processing.require_job(registry.get(resource_id).job)
    if job.status.is_running():
        raise exceptions.MinkHTTPException(
            return_code=return_codes.PROCESS_RUNNING, info="Cannot uninstall while a job is running"
        )

    try:
        job = processing.require_job(job)
        warnings, output = job.uninstall_korp()
        return utils.response(
            return_code=return_codes.UNINSTALLED, info="Uninstalled from Korp", output=output, warnings=warnings
        )
    except Exception as e:
        raise exceptions.MinkHTTPException(
            return_code=return_codes.FAILED_UNINSTALLING, info=f"Error when uninstalling from Korp: {e}"
        ) from e


@router.put(
    "/strix/install/{resource_id}",
    operation_id="install-strix",
    response_model=models.StatusResponse,
    responses={
        **models.common_auth_error_responses,
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": models.ErrorResponse500,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FAILED_QUEUING.message,
                        "return_code": return_codes.FAILED_QUEUING.code,
                        "info": "BaseException",
                    }
                }
            },
        },
    },
)
async def install_strix(auth_data: dict = Depends(AUTH_CORPUS_WRITE)) -> JSONResponse:
    """Install the corpus in Strix with Sparv.

    ### Example

    ```bash
    curl -X PUT '{{host}}/corpus/strix/install/<resource_id>' -H 'Authorization: Bearer YOUR_JWT'
    ```
    """
    resource_id = auth_data["resource_id"]

    # Get info_item, check for changes and remove exports if necessary
    sources_deleted = config_changed = False
    try:
        info_item = route_utils.get_info_from_auth(auth_data)
        if info_item.job.started:
            _, sources_deleted, config_changed = storage.get_file_changes(resource_id, info_item)
    except Exception as e:
        raise exceptions.MinkHTTPException(return_code=return_codes.FAILED_RUNNING, info=str(e)) from e
    if sources_deleted or config_changed:
        sparv_output = ""
        try:
            job = processing.require_job(info_item.job)
            success, sparv_output = job.clean_export()
            assert success
        except Exception as e:
            raise exceptions.MinkHTTPException(
                return_code=return_codes.FAILED_RUNNING,
                info=f"Failed to remove outdated export files before running Sparv: {e}",
                sparv_message=sparv_output,
            ) from e

    # Queue job
    job = processing.require_job(info_item.job)
    try:
        job = registry.add_to_queue(job)
    except Exception as e:
        raise exceptions.MinkHTTPException(return_code=return_codes.FAILED_QUEUING, info=str(e)) from e

    job.set_status(Status.waiting, ProcessName.strix)

    # Wait a few seconds to check whether anything terminated early
    time.sleep(3)
    return utils.response(return_code=return_codes.CHECKED_STATUS, **route_utils.make_status_response(info_item))


@router.delete(
    "/strix/uninstall/{resource_id}",
    operation_id="uninstall-strix",
    response_model=models.BaseResponse,
    responses={
        status.HTTP_200_OK: {
            "content": {
                "application/json": {
                    "example": {
                        "status": "success",
                        "message": return_codes.UNINSTALLED.message,
                        "return_code": return_codes.UNINSTALLED.code,
                        "info": "Uninstalled from Strix",
                    }
                }
            }
        },
        **models.common_auth_error_responses,
        status.HTTP_503_SERVICE_UNAVAILABLE: {
            "model": models.BaseErrorResponse,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.PROCESS_RUNNING.message,
                        "return_code": return_codes.PROCESS_RUNNING.code,
                        "info": "Cannot uninstall while a job is running",
                    }
                }
            },
        },
        status.HTTP_500_INTERNAL_SERVER_ERROR: {
            "model": models.ErrorResponse500,
            "content": {
                "application/json": {
                    "example": {
                        "status": "error",
                        "message": return_codes.FAILED_UNINSTALLING.message,
                        "return_code": return_codes.FAILED_UNINSTALLING.code,
                        "info": "Error when uninstalling from Strix",
                    }
                }
            },
        },
    },
)
async def uninstall_strix(auth_data: dict = Depends(AUTH_CORPUS_WRITE)) -> JSONResponse:
    """Uninstall the corpus from Strix with Sparv.

    ### Example

    ```bash
    curl -X DELETE '{{host}}/corpus/strix/uninstall/<resource_id>' -H 'Authorization: Bearer YOUR_JWT'
    ```
    """
    resource_id = auth_data["resource_id"]
    # Check if there is an active job
    job = processing.require_job(registry.get(resource_id).job)
    if job.status.is_running():
        raise exceptions.MinkHTTPException(
            return_code=return_codes.PROCESS_RUNNING, info="Cannot uninstall while a job is running"
        )

    try:
        job = processing.require_job(job)
        warnings, output = job.uninstall_strix()
        return utils.response(
            message=return_codes.UNINSTALLED.message,
            return_code=return_codes.UNINSTALLED.code,
            info="Uninstalled from Strix",
            warnings=warnings,
            output=output,
        )
    except Exception as e:
        raise exceptions.MinkHTTPException(
            return_code=return_codes.FAILED_UNINSTALLING, info=f"Error when uninstalling from Strix: {e}"
        ) from e
